#!/bin/sh
# dzen & conky starter

CFG='.dzconkyrc'
BG='#101010'
FG='#ffffff'
X=0
Y=1060
HEIGHT=20
WIDTH=1920
FONT='-*-terminus-medium-r-*-*-16-*-*-*-*-*-*-*'

conky -c $CFG | sh | dzen2 -x $X -y $Y -e '' -bg $BG -fg $FG -w $WIDTH -h $HEIGHT -ta c -xs 1 -fn $FONT -p
